# Generated by Django 5.0 on 2023-12-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="/default.png", upload_to="user_photos"),
        ),
    ]
