# Generated by Django 5.0 on 2023-12-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="user_photos"),
        ),
    ]
